### ISSUE TITLE
[PROGRESS] Abjt03

### ISSUE THREAD

**Issue by Abjt03** [Codezilla-Club/30-Days-of-Code#10]
## Participant Details
**Name/Nickname:** Abjt03
**Pronouns:** he/him
**Domain:** Machine Learning

I'm a student at SRM interested in Machine Learning

## Milestones
- [ ] Code for 30 days

- [ ] I want to learn about Machine Learning Basics
- [ ] I want to get a certificate in Machine Learning
- [ ] I want to create a complex ML project

## Checklist
- [ ] I've read the Code of Conduct, Rules and Guidelines
- [ ] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by Abjt03** [comment]
Day 1

## What I Learned Today
- Was pretty sick so took my meds and slept through the day

## What I'll Learn Tomorrow
- Start looking into the resources for DS-ML
- Set up Dev Environment (probably Atom cos I'm used to it)
- See where we go from here 😉

**Comment by Abjt03** [comment]
Sorry for the delay
Had some issues with login on GitHub
That said....

Day 2

## What I Learned Today
- Python Fundamentals 
- Variables 
- Relational, Logical Operators and Expressions
- Set up Atom dev environment

## What I'll Learn Tomorrow
- Conditional Statements
- Looping in python

**Comment by Abjt03** [comment]
Day 3

## What I Learned Today
- Conditional Statements
- Looping in python

## What I'll Learn Tomorrow
- Lists, Dictionaries, Sets and Tuples

**Comment by Abjt03** [comment]
Day 4

## What I Learned Today
- Lists, Dictionaries, Sets and Tuples

## What I'll Learn Tomorrow
- Functions and Recursion

**Comment by Abjt03** [comment]
Day 5

## What I Learned Today
- Functions and Recursion

## What I'll Learn Tomorrow
- Oops in Python

**Comment by Abjt03** [comment]
Day 6

## What I Learned Today
- Oops in Python

## What I'll Learn Tomorrow
- Intro into Data Analytics

**Comment by Abjt03** [comment]
Day 7

## What I Learned Today
- Intro to Data Analytics
- Markdown Language
- Week 1 Project : [Here](https://github.com/Abjt03/Codezilla-30-Days-Of-Code-DS-ML-Mar-2022/tree/main/Week-1)

## What I'll Learn Tomorrow
- Python Libaries used in Data Analytics

**Comment by Abjt03** [comment]
Day 8

## What I Learned Today
- Numpy

## What I'll Learn Tomorrow
- Matplotlib

**Comment by Abjt03** [comment]
Day 9

## What I Learned Today
- Took a break

## What I'll Learn Tomorrow
- Matplotlib
