### ISSUE TITLE
POOJHA 

### ISSUE THREAD

**Issue by poojha0203** [Codezilla-Club/30-Days-of-Code#13]
POOJHA
SHE
DSA

HII, I am Poojha Ranganath. I am a 3rd year Btech cse bs in SRM. I am an enthusiastic and inquisitive person. I speak french, eng, Hindi and Tamil.

## Milestones
- [x] Code for 30 days
- [ ] Make my DSA skills stronge

## Checklist
- [x] I've read the Code of Conduct, Rules, and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by cdkushan** [comment]
Please share ur updates!

**Comment by poojha0203** [comment]
DAY 1 
Learnt BASICS

**Comment by poojha0203** [comment]
DAY 2 
ARRAYS BASICS

**Comment by cdkushan** [comment]
Keep doin! Do reach us if u hv any issues!✨

**Comment by poojha0203** [comment]
sure
