### ISSUE TITLE
[PROGRESS] Username

### ISSUE THREAD

**Issue by ks9067** [Codezilla-Club/30-Days-of-Code#14]
## Participant Details
**Name/Nickname:**Kunal Sugandhi 
**Pronouns:** He
**Domain:**

## Milestones
- [ ] Code for 30 days
 Hacker

## Checklist
- [ ] I've read the Code of Conduct, Rules and Guidelines
- [ ] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by Aditi-Athreya** [comment]
Please make sure you specify your domain.
