### ISSUE TITLE
[PROGRESS] ABIraj2

### ISSUE THREAD

**Issue by ABIraj2** [Codezilla-Club/30-Days-of-Code#15]
## Participant Details
**Name/Nickname:**ABI
**Pronouns:**He/Him
**Domain:**Android development

## Milestones
- [ ] Code for 30 days

- [ ] get a general idea on android dev 

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by ghost** [comment]
Day 1

## What I Learned Today
- installed android studio
- created a people counter app by following a tutorial and understood the kotlin code as much as i could
- tested it on my phone


## What I'll Learn Tomorrow
- kotlin basics & fundamentals

**Comment by ghost** [comment]
Day 2

## What I Learned Today
- var , val
- operators 
- if else
- learnt about views
- looked into xml 


## What I'll Learn Tomorrow
- loops
- oop in kotlin
- start designing signup page

**Comment by ghost** [comment]
Day 3

## What I Learned Today
- relative layout
- linear layout
- layout weight



## What I'll Learn Tomorrow
- start oop
- try making signup page with xml
- start calculator app
