### ISSUE TITLE
[PROGRESS] Princy

### ISSUE THREAD

**Issue by Princy02** [Codezilla-Club/30-Days-of-Code#18]
## Participant Details
**Name/Nickname:** Princy
**Pronouns:** she/her
**Domain:** Machine Learning

I am fast learner and quite flexible person.
## Milestones
- [ ] Code for 30 days
- [ ] Learn new things about machine learning.

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by Princy02** [comment]
Day 1

## What I Learned Today
- I learnt about the different domains on 30 days of code.

## What I'll Learn Tomorrow
-  I'd love to learn the machine learning concepts.
