### ISSUE TITLE
[PROGRESS] Rohith

### ISSUE THREAD

**Issue by Rohithv04** [Codezilla-Club/30-Days-of-Code#19]
## Participant Details
**Name/Nickname:** Rohith
**Pronouns:** He/Him
**Domain:** DSA

Hi, this is Rohith from CSBS SRMRMP, I'm here to make some progress in DSA and to improve my programming skills

## Milestones
- [ ] Code for 30 days
- [ ] I would like to learn Python DSA
- [ ] I want to be consistent and to learn new things every day

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor
