### ISSUE TITLE
[PROGRESS]  crypt3d-c00kie

### ISSUE THREAD

**Issue by crypt3d-c00kie** [Codezilla-Club/30-Days-of-Code#21]
## Participant Details
**Name/Nickname: Jac**
**Pronouns: He/Him**
**Domain: Web Development**

## Milestones
- [x] Start
- [ ] Halfway
- [ ] Completion

- [ ] Get familiar with the basics
- [ ] Make a working model with what i learnt

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by crypt3d-c00kie** [comment]
Day 1

## What I Learned Today
- Basic HTML and HTML5

## What I'll Learn Tomorrow
- More about HTML5 elements

**Comment by crypt3d-c00kie** [comment]
Day 2

## What I Learned Today
- HTML 5 Elements

## What I'll Learn Tomorrow
- Lists, Text fields and Anchors!

**Comment by crypt3d-c00kie** [comment]
Day 3

## What I Learned Today
- Lists and Anchors

## What I'll Learn Tomorrow
- Form creation w/ Radio Button/check boxes and other elements

**Comment by crypt3d-c00kie** [comment]
Day 4

## What I Learned Today
- Form Creation w/ HTML

## What I'll Learn Tomorrow
- Basic CSS

**Comment by crypt3d-c00kie** [comment]
Day 5

## What I Learned Today
- Basic CSS

## What I'll Learn Tomorrow
- CSS Flexbox

**Comment by crypt3d-c00kie** [comment]
Day 6

## What I Learned Today
- CSS Flexbox basics

## What I'll Learn Tomorrow
- Flexbox (Maybe i need a lil more time on this)

**Comment by crypt3d-c00kie** [comment]
Day 7

## What I Learned Today
- More flexbox

## What I'll Learn Tomorrow
- sass basics

**Comment by crypt3d-c00kie** [comment]
Day 8

## What I Learned Today
- Sass Styling

## What I'll Learn Tomorrow
- Revision on CSS positioning

**Comment by crypt3d-c00kie** [comment]
Day 9

## What I Learned Today
- Revision on CSS positioning

## What I'll Learn Tomorrow
- Revision on flexbox

**Comment by crypt3d-c00kie** [comment]
Day 10

## What I Learned Today
- Revision on Flexboxx

## What I'll Learn Tomorrow
- Starting JS for the first time ever.

**Comment by crypt3d-c00kie** [comment]
Day 11

## What I Learned Today
- A little introduction to JS

## What I'll Learn Tomorrow
- Bootstrap intro ( realized i need to do something before going into js)
