### ISSUE TITLE
[PROGRESS] J chalwin Ajay

### ISSUE THREAD

**Issue by Ajay072** [Codezilla-Club/30-Days-of-Code#22]
## Participant Details
**Name/Nickname:**Aj
**Pronouns:**He/Him
**Domain:**Web development

## Milestones
- [ ] Code for 30 days

I wanna be able to develop simple websites
## Checklist
- [ ] I've read the Code of Conduct, Rules and Guidelines
- [ ] I've named this Issue as indicated
- [ ] I've been assigned a mentor
