### ISSUE TITLE
[PROGRESS] uniquesnaha

### ISSUE THREAD

**Issue by uniquesnaha** [Codezilla-Club/30-Days-of-Code#23]
## Participant Details
**Name/Nickname:** snaha
**Pronouns:** she/her
**Domain:** DSA

## Milestones
- [ ] Code for 30 days
- [ ] Learn graphs and trees
- [ ] create min.2 programs on my own

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by uniquesnaha** [comment]
## What I learned today
Programming language- C++, Basics of DSA
## What I'll learn tomorrow
Arrays and Strings

**Comment by uniquesnaha** [comment]
## What I learned today
Arrays and strings
## What I'll learn tomorrow
Linked lists

**Comment by uniquesnaha** [comment]
## What I learned today
Linked lists
## What I'll learn tomorrow
Stacks and Queues

**Comment by cdkushan** [comment]
Great goin✨✨✨ keep the spirit up!

**Comment by uniquesnaha** [comment]
## What I learned today
stacks and queues
## What I'll learn tomorrow
stacks and queues- linked list representation

**Comment by cdkushan** [comment]
Great learning! Do reach out us if u hv any issues!

**Comment by uniquesnaha** [comment]
> Great learning! Do reach out us if u hv any issues!

Yup sure✌️

**Comment by uniquesnaha** [comment]
## What I learned today
stacks and queues- linked list representation
## What I'll learn tomorrow
double ended queues, priority queues, circular queues
