### ISSUE TITLE
[PROGRESS] Govindaraj S

### ISSUE THREAD

**Issue by GovindarajSubramani03** [Codezilla-Club/30-Days-of-Code#24]
## Participant Details
**Name/Nickname:** Govind
**Pronouns:** he/him
**Domain:** app development

 
This is Govindaraj currently pursuing CSE IOT first year.
I have chosen app development in this 30days of code 

## Milestones
- [ ] Code for 30 days

- [ ] I wanted to learn app development in these 30days.
## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor
