### ISSUE TITLE
[PROGRESS] Bhar-02

### ISSUE THREAD

**Issue by Bhar-02** [Codezilla-Club/30-Days-of-Code#25]
## Participant Details
**Name/Nickname:** Bhar
**Pronouns:** she/her
**Domain:** Data structures and algorithms

## Milestones
- [x] Code for 30 days

- I want to learn regression
- I want to learn trees, graph and linked lists.

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by cdkushan** [comment]
Pls share ur updates!
