### ISSUE TITLE
[PROGRESS] GayathriTK

### ISSUE THREAD

**Issue by GayathriTK** [Codezilla-Club/30-Days-of-Code#28]
## Participant Details
**Name/Nickname:** Gayu
**Pronouns:** She/Her
**Domain:** Machine Learning

## Milestones
- [ ] Code for 30 days

- [ ] I would like to learn Supervised Learning
- [ ] I would like to learn Unsupervised Learning
- [ ] I would like to Semi-Supervised Learning
- [ ] I would like to Reinforcement
- [ ] I want to finish a book on 

## Checklist
- [ ] I've read the Code of Conduct, Rules and Guidelines
- [ ] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by GayathriTK** [comment]
### **Day 1**

**_What I learnt today_**
- Went through the roadmap
-  Googled about the basic topics given

_**What I'll learn tomorrow**_
- Basics of Object Oriented Programming in Python
