### ISSUE TITLE
[PROGRESS] rohankumar1234590

### ISSUE THREAD

**Issue by rohankumar1234590** [Codezilla-Club/30-Days-of-Code#29]
## Participant Details
**Name/Nickname:**Rohan
**Pronouns:**He/His
**Domain:**Data Structure 

## Milestones
- [ ] Code for 30 days

- [ ] Learn Linked List
- [ ] Learn lists
- [ ] Get a good command on Dsa
- [ ] Solve Atleast 100+ Codes

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by kumarrohan9724** [comment]
DAY N

## What I have learned Today
- Revise Basics of C++ (Loops, functions, pointers, and basic operations)

## What I will learn Tomorrow 
- Arrays
