### ISSUE TITLE
[PROGRESS] Shonelle

### ISSUE THREAD

**Issue by ShonelleAndrea** [Codezilla-Club/30-Days-of-Code#30]
## Participant Details
**Name/Nickname:**Shonelle
**Pronouns:**she/her
**Domain:**Android development

## Milestones
- [ ] Code for 30 days

- [ ] I would like to learn coding to improvise my skillset 
- [ ] To develop an app from scratch

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor
