### ISSUE TITLE
[PROGRESS] Sarah17

### ISSUE THREAD

**Issue by sarahphilip17** [Codezilla-Club/30-Days-of-Code#33]
## Participant Details
**Name/Nickname:** Sarah
**Pronouns:** she/her
**Domain:** Android development

## Milestones
- [ ] Code for 30 days

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by sarahphilip17** [comment]
Day 1

## What I Learned Today
- Looked through the roadmap
- Learnt which language is better for AD
- Installed Android Studio

## What I'll Learn Tomorrow
- Set up Android Studio
- Basics of java
