### ISSUE TITLE
[PROGRESS] Vasudha511

### ISSUE THREAD

**Issue by Vasudha511** [Codezilla-Club/30-Days-of-Code#36]
## Participant Details
**Name/Nickname:** Vasu
**Pronouns:** She/Her
**Domain:** DSA

 Enthusiastic learner

## Milestones
- [ ] Code for 30 days

- [ ] Become strong in fundamentals of DSA
- [ ] Learn to solve problems using python
- [ ] Learn to write efficient codes 

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by VasudhaCN** [comment]
Day 1

## What I Learned Today
- basic data types 
- control flow

## What I'll Learn Tomorrow
- lists, arrays
- binary search
