### ISSUE TITLE
[PROGRESS] Suryateja2002

### ISSUE THREAD

**Issue by SuryaTeja2002** [Codezilla-Club/30-Days-of-Code#37]
## Participant Details
**Name/Nickname:** Surya
**Pronouns:** He/Him
**Domain:** Web Development

I am a tech enthusiastic, who believes doing is much better than thinking to do.
## Milestones
- [ ] Code for 30 days

- [ ] I want to learn javascript.
- [ ] I wanna make a portfolio website for myself.
- [ ] I wanna build consistency in coding.
## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by SuryaTeja2002** [comment]
Day 1

## What I Learned Today
- I've revised Html tags.

## What I'll Learn Tomorrow
- I'd like to learn the basics of CSS.
- and know more about internet basics and SDLC

**Comment by SuryaTeja2002** [comment]
Day 2

## What I Learned Today
-  what is Internet basics and how does it work.
-  I've gone through HTTP,HTTPS,SSL,TLS.
-  about SDLC.

## What I'll Learn Tomorrow
- Basics of git.
- Basics of CSS.

**Comment by SuryaTeja2002** [comment]
Day 3

## What I Learned Today
- Installation of git.
- git commands & how to push into github repo using git.

## What I'll Learn Tomorrow
- probably Basics of CSS.
- Practice with HTML.

**Comment by ThanviChowdhary** [comment]
Great progress Surya!

In CSS, if you get struck anywhere check this out
[<https://developer.mozilla.org/en-US/docs/Web/CSS/Reference>]()

**Comment by SuryaTeja2002** [comment]
Day 4

## What I Learned Today
- I practiced HTML forms.
- Basics of CSS(started)

## What I'll Learn Tomorrow
- Basics of CSS(Practice)

**Comment by SuryaTeja2002** [comment]
Day 5

## What I Learned Today
- completed this week's project about creating a low fidelity design 
   [tap here](https://drive.google.com/drive/folders/1dNdy6rg226U2dxfH5ARHBjToXZ3UuKAi?usp=sharing)
- More about CSS

## What I'll Learn Tomorrow
- I'll stick with CSS maybe

**Comment by SuryaTeja2002** [comment]
Day 6

## What I Learned Today
- a video about web development by CS50 Mr.David
- Practice with CSS

## What I'll Learn Tomorrow
- few more Tutorials.

**Comment by SuryaTeja2002** [comment]
Day 7

## What I Learned Today
- Continued with CS50 Video about web development.

## What I'll Learn Tomorrow
- to Start HTML project.

**Comment by SuryaTeja2002** [comment]
Day 8

## What I Learned Today
-  Thought about HTML Project
-  some Practice

## What I'll Learn Tomorrow
- HTML project

**Comment by SuryaTeja2002** [comment]
Day 9

## What I Learned Today
- Introduction to Javascript

## What I'll Learn Tomorrow
- Javascript 
- HTML project

**Comment by SuryaTeja2002** [comment]
Day 10

## What I Learned Today
- Little bit of Javascript

## What I'll Learn Tomorrow
- Javascript

**Comment by SuryaTeja2002** [comment]
Day 11

## What I Learned Today
-  Practice with css

## What I'll Learn Tomorrow
- More practice
