### ISSUE TITLE
[PROGRESS] rajcharanthecoder

### ISSUE THREAD

**Issue by rajcharanthecoder** [Codezilla-Club/30-Days-of-Code#38]
## Participant Details
**Name/Nickname:**Raj Charan
**Pronouns:**He/Him
**Domain:**Web Development

Hey Folks my name is Gangisetty Raj Charan from SRM university Kattankulathur campus. A techie enthusiast and code lover. I learnt web development basics(HTML, CSS).practising various coding questions on various websites like CodeChef,codeforces, Hackerrank, Geeks for Geeks etc. Wanna connect with me https://linktr.ee/GANGISETTY_RAJ_CHARAN
## Milestones
- [ ] Code for 30 days

- [ ] Want to learn Html and CSS properly and be able to apply them in code
- [ ] Learning backend in a rough idea
- [ ] Want to learn full-stack (Only a basic idea and able to apply basic idea)
 

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor
