### ISSUE TITLE
[PROGRESS] Sree Ramya

### ISSUE THREAD

**Issue by sree-0239** [Codezilla-Club/30-Days-of-Code#41]
## Participant Details
**Name/Nickname:** Sree
**Pronouns:** she/her
**Domain:** machine learning

i am 2nd year student with majority of computer science in srm university.

## Milestones
- [ ] Code for 30 days

-[ ] To develop a good skills in machine learning
-[ ] To become strong with the basics of machine learning

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by sree-0239** [comment]
Day 1

## What I Learned Today
- i learnt how to complete this 30 days of code of codezilla club

## What I'll Learn Tomorrow
- i will learning introduction of my respective domine.

**Comment by ghost** [comment]
Day 2

## What I Learned Today
- connected with the community
- learnt introduction of web development 
- learnt what is frontend web development

## What I'll Learn Tomorrow
- to get idea on what are web design web developer tools

**Comment by ghost** [comment]
Day 3

## What I Learned Today
- Revised yesterday topic
- studied what are web design web developer tools

## What I'll Learn Tomorrow
- start learning  basics of html

**Comment by charitharyan** [comment]
Hey Sree Ramya, please do join the discord server as soon as possible
https://discord.gg/RTamqMWnTb

And please check your Milestones, one checkbox is missing

**Comment by charitharyan** [comment]
Hey Sree Ramya, please do join the discord server as soon as possible
https://discord.gg/RTamqMWnTb

And please check your Milestones, one checkbox is missing

**Comment by ghost** [comment]
Day 4

## What I Learned Today
- learnt html basics

## What I'll Learn Tomorrow
- to get grip on html

**Comment by ghost** [comment]
Day 5

## What I Learned Today
- html practise 

## What I'll Learn Tomorrow
- more practise in html

**Comment by ghost** [comment]
Day 6

## What I Learned Today
- done more practise on html

## What I'll Learn Tomorrow
-learn css

**Comment by ghost** [comment]
Day 7

## What I Learned Today
- learnt css

## What I'll Learn Tomorrow
- css practise

**Comment by ghost** [comment]
Day 8

## What I Learned Today
- practise css 

## What I'll Learn Tomorrow
- more practise on css
