### ISSUE TITLE
[PROGRESS] Username

### ISSUE THREAD

**Issue by Marshmallows777** [Codezilla-Club/30-Days-of-Code#42]
## Participant Details
**Name/Nickname:**
**Pronouns:**
**Domain:**

## Milestones
- [x] Code for 30 days

## Checklist
- [ ] I've read the Code of Conduct, Rules and Guidelines
- [ ] I've named this Issue as indicated
- [ ] I've been assigned a mentor
