### ISSUE TITLE
[PROGRESS] navya09jain

### ISSUE THREAD

**Issue by navya09jain** [Codezilla-Club/30-Days-of-Code#43]
## Participant Details
**Name/Nickname:*Navya*
**Pronouns:*she/her*
**Domain:*Web development*

hi, I am navya and I am enthusiastic about web development 

## Milestones
- [x] Code for 30 days
- Project link: https://github.com/navya09jain/Hold-to-Win-

Learn web development as much as I can.
Complete my tasks.

## Checklist
- [x] I've read the Code of Conduct, Rules, and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by navya09jain** [comment]
Day 0:

## What I Learned Today
- I've learned about how the program works

## What I'll Learn Tomorrow
- Web development

**Comment by navya09jain** [comment]
Day 1:

## What I Learned Today
- Internet basics

## What I'll Learn Tomorrow
- Github basics probably!

**Comment by navya09jain** [comment]
Day 2:

## What I Learned Today
- brushed up HTML language 
- looked for project ideas online

## What I'll Learn Tomorrow
- GitHub and SDLC

**Comment by ThanviChowdhary** [comment]
Hello Navya!

1.Check the markdown in the intro
2.Also add check box for your milestones

**Comment by navya09jain** [comment]
Okay sure :)

**Comment by navya09jain** [comment]
Day 3:

## What I Learned Today
- brushed up creating a repository in Github
- continued my javascript course

## What I'll Learn Tomorrow
- will research the project.

**Comment by ThanviChowdhary** [comment]
Great progress Navya !
Change the markdown soon as suggested in previous comment

**Comment by navya09jain** [comment]
I didn’t get you . Change the markdown as in? Sent from Mail for Windows From: ThanviSent: 05 March 2022 11:44To: Codezilla-Club/30-Days-of-CodeCc: navya jain; AuthorSubject: Re: [Codezilla-Club/30-Days-of-Code] [PROGRESS] navya09jain (Issue #43) Great progress Navya !Change the markdown soon as suggested in previous comment—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by navya09jain** [comment]
> Great progress Navya! Change the markdown soon as suggested in the previous comment

Hey, actually I didn't get you! How could I change the markdown and for what
??

**Comment by navya09jain** [comment]
I also had a doubt regrading this week's assignment

**Comment by ThanviChowdhary** [comment]
> > Great progress Navya! Change the markdown soon as suggested in the previous comment
> 
> Hey, actually I didn't get you! How could I change the markdown and for what ??

1.Add ** after your name, pronouns and domain(to make it bold)
2.Add checkbox to the last two milestones too
- [ ] Learn web development as much as I can.
- [ ] Complete my tasks

**Comment by ThanviChowdhary** [comment]
> I also had a doubt regrading this week's assignment

What's your doubt? This week's assignment is to design a website (framework/idea of a website)
To get an idea about that ,check this out👇🏻

**Comment by ThanviChowdhary** [comment]
![WhatsApp Image 2022-03-05 at 12 15 12 PM](https://user-images.githubusercontent.com/77197460/156871942-d7d8164d-12ca-4d00-9140-f13b3aad02df.jpeg)

**Comment by navya09jain** [comment]
Day 4:

## What I Learned Today
- completed this week's assignment, created a low fidelity prototype
link: https://drive.google.com/file/d/1LX9FGZyDxbJZX263CyUpoFIflUpBfV9K/view?usp=sharing
I have not used any software instead designed it on paper, do check it out.

## What I'll Learn Tomorrow
- continue with my javascript course.

**Comment by ThanviChowdhary** [comment]
Awesome!

**Comment by navya09jain** [comment]
Day 5:

## What I Learned Today
- have learned about the basics of Mozilla

## What I'll Learn Tomorrow
-will start with the HTML project

**Comment by navya09jain** [comment]
Day 6:

## What I Learned Today
- continued my Javascript course

## What I'll Learn Tomorrow
- will start with the HTML project

**Comment by navya09jain** [comment]
Day 7:

## What I Learned Today
- started with my HTML project

## What I'll Learn Tomorrow
- continue with the HTML project

**Comment by navya09jain** [comment]
Day 8:

## What I Learned Today
- I was actually busy so haven't done anything much and also forgot to update the attendance

## What I'll Learn Tomorrow
- continue my project for this week

**Comment by navya09jain** [comment]
Day 9:

## What I Learned Today
- continued my javascript course
- progress for this week's project

## What I'll Learn Tomorrow
- complete the project
