### ISSUE TITLE
[PROGRESS] Username

### ISSUE THREAD

**Issue by GitHubVin99** [Codezilla-Club/30-Days-of-Code#45]
## Participant Details
**Name/Nickname:** Vinod
**Pronouns:** Him/He
**Domain:** DSA

## Milestones
- [ ] Code for 30 days
- [ ]  Prepare DSA for placements

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by ghost** [comment]
Day 0

## What I Learned Today
- Learnt about the program

## What I'll Learn Tomorrow
- Data structures and algorithm implementation through a question a day

**Comment by ghost** [comment]
Day 1

## What I Learned Today
- Went through the dsa roadmap and attempted 3 questions 

## What I'll Learn Tomorrow
- Arrays, Stacks
