### ISSUE TITLE
[PROGRESS] Snigdha031-on-github

### ISSUE THREAD

**Issue by snigdha031** [Codezilla-Club/30-Days-of-Code#47]
## Participant Details
**Name/Nickname:**Snigdha
**Pronouns:**she/her
**Domain:**Machine Learning

## Milestones
- [ ] Code for 30 days

-[ ] Understand ML Algorithm 
-[ ]Should be strong in the basics of ML

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [ ] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by GopinathBalaji** [comment]
Hey Snigdha
Please make sure your checkboxes are correct.
