### ISSUE TITLE
[PROGRESS] Roshi-on-Github

### ISSUE THREAD

**Issue by RoshiniMadan** [Codezilla-Club/30-Days-of-Code#48]
## Participant Details
**Name/Nickname:** Roshi
**Pronouns:** she/her
**Domain:** web development

 
 Hi, I'm a web developer enthusiast... always learning while coding... 

## Milestones
- [x] Code for 30 days

- [x] learning more about web development
- [x] completing my daily task 

# Checklist
- [x] I've read the Code of Conduct, Rules, and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by RoshiniMadan** [comment]
Day 2

## What I Learned Today
-  learnt about html 

## What I'll Learn Tomorrow
- gonna learn about css

**Comment by RoshiniMadan** [comment]
Day 3

## What I Learned Today
-  basics about HTTP and HTTPS 
- differences between GIT and GITHUB 
- explanation about SDLC 
- few basics in CSS 

## What I'll Learn Tomorrow
-  need to learn more about SDLC and a few syntaxes and styles in CSS

**Comment by Akshara604** [comment]
Hi Roshi
Please make sure your checkboxes are correct.

**Comment by RoshiniMadan** [comment]
I hope its crt now

**Comment by RoshiniMadan** [comment]
Day 4

## What I Learned Today
-  searching more content about SDLC, but not getting ideas regarding the project 
- And a few tags in HTML

## What I'll Learn Tomorrow
- need to learn more about SDLC

**Comment by RoshiniMadan** [comment]
Day 5

## What I Learned Today
-  completed my 1st-week project
-  https://drive.google.com/file/d/16mjqPYykdqNRqQNaDMRo1bH7wavJev7X/view?usp=sharing


## What I'll Learn Tomorrow
- need to continue with HTML  and CSS deeper

**Comment by RoshiniMadan** [comment]
Day 6

## What I Learned Today
- attended the event and participated in the quiz .
-  done with html forms , form attributes , form elements , input attributes. 
-  done with HTML color codes .

## What I'll Learn Tomorrow
-  need to go on with HTML forms and few topics in CSS

**Comment by RoshiniMadan** [comment]
Day 7

## What I Learned Today
-  continued learning HTML and CSS

## What I'll Learn Tomorrow
-  started working on with HTML project

**Comment by RoshiniMadan** [comment]
Day 8 ( 8.3.2022)

## What I Learned Today
-  continued learning with CSS syntaxes.
- working on with HTML project.

## What I'll Learn Tomorrow
-  continuing with the HTML project. 
-  should continue with CSS.

**Comment by RoshiniMadan** [comment]
Day 9 (9.3.2022)

## What I Learned Today
- continued learning with link basics, in-page links, and link styles.
- working on the  HTML project.

## What I'll Learn Tomorrow
- should continue my HTML project.
- start learning navigation menus and layouts in CSS and HTML.

**Comment by RoshiniMadan** [comment]
Day 10 (10.3.2022)

## What I Learned Today
-  continued with the HTML project.

## What I'll Learn Tomorrow
-  should continue with CSS layouts.

**Comment by RoshiniMadan** [comment]
Day 11(11.03.22)

## What I Learned Today
- nothing much today, just stuck with college kinds of stuff

## What I'll Learn Tomorrow
- should complete my  HTML project.
- And should complete more topics in CSS.

**Comment by RoshiniMadan** [comment]
Day 12(12.03.2022)

## What I Learned Today
- came to the finishing stage of the HTML project.

## What I'll Learn Tomorrow
- little more topics left in CSS, that will complete soon.
- should move on with javascript.

**Comment by RoshiniMadan** [comment]
Day 13(13.03,2022)

## What I Learned Today
- I got stuck up in submitting my project, I will submit it as soon as possible.

## What I'll Learn Tomorrow
- should start learning javascript.

**Comment by RoshiniMadan** [comment]
Day 14(14.03.2022)

## What I Learned Today
-  completed my HTML project.
- https://roshinimadan.github.io/FAVORITE/

## What I'll Learn Tomorrow
-  will learn  more in css .
- continue with javascript .

**Comment by RoshiniMadan** [comment]
Day 15(15.03.2022)

## What I Learned Today
- continued with layouts - block spacing in CSS.

## What I'll Learn Tomorrow
- should continue with arranging the page and positioning in CSS.

**Comment by RoshiniMadan** [comment]
Day 16(16.03.2022)

## What I Learned Today
-  continued learning with CSS. 
- and few basics in javascript.

## What I'll Learn Tomorrow
- try to complete CSS and should continue with javascript.

**Comment by RoshiniMadan** [comment]
Day 17 (17.03.2022)

## What I Learned Today
-  nothing much today, got stuck with my clg stuffs.

## What I'll Learn Tomorrow
- should start with this week project.

**Comment by RoshiniMadan** [comment]
Day 18( 18.03.2022) 

## What I Learned Today
-  going with CSS 
- And this week project

## What I'll Learn Tomorrow
   
- Should continue with project

**Comment by RoshiniMadan** [comment]
Day 19(19.03.2022)

## What I Learned Today
- completed my 3rd-week project.
- https://roshinimadan.github.io/WEEK-3/

## What I'll Learn Tomorrow
- should continue with javascript

**Comment by RoshiniMadan** [comment]
Day 21(21.03.2022)

## What I Learned Today
- unable to post by progress yesterday since I was not feeling well.
- going on with javascript basics.

## What I'll Learn Tomorrow
- continue with javascript.

**Comment by RoshiniMadan** [comment]
Day 23(23.03.2022)

## What I Learned Today
- unable to post again due to my illness, I am sorry.
- going on with javascript syntaxes.

## What I'll Learn Tomorrow
- should start with the 4th-week project.

**Comment by RoshiniMadan** [comment]
Day 24(24.03.2022)

## What I Learned Today
- continued with javascript.
- continuing with my project.

## What I'll Learn Tomorrow
- continue with javascript operators.

**Comment by RoshiniMadan** [comment]
Day 25(25.03.2022)

## What I Learned Today
- working on with the project

## What I'll Learn Tomorrow
- should continue with javascript

**Comment by RoshiniMadan** [comment]
Day 27(27.03.2022)

## What I Learned Today
- unable to post my progress due to my college stuff.
- continuing with javascript

## What I'll Learn Tomorrow
- should continue with my project.

**Comment by RoshiniMadan** [comment]
Day 29(29.3.2022)

## What I Learned Today
- got stuck with my project, will try to complete it.
- should continue with javascript

## What I'll Learn Tomorrow
- continue with javascript

**Comment by RoshiniMadan** [comment]
Day 30(30.03.2022)

## What I Learned Today
- continuing with JS comparisons. 
- completed the week project.

## What I'll Learn Tomorrow
- challenge completed.
- thank you for this amazing event.
