### ISSUE TITLE
[PROGRESS] Username

### ISSUE THREAD

**Issue by Chirag21-11** [Codezilla-Club/30-Days-of-Code#50]
## Participant Details
**Name/Nickname:** Chirag
**Pronouns:** He
**Domain:** Web Development

## Milestones
- [ ] Code for 30 days

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [ ] I've named this Issue as indicated
- [ ] I've been assigned a mentor
