### ISSUE TITLE
[PROGRESS] Rahul-on-github

### ISSUE THREAD

**Issue by Rahul-on-github** [Codezilla-Club/30-Days-of-Code#52]
## Participant Details
**Name/Nickname:** Rahul
**Pronouns:** He/Him
**Domain:** Data Structures and Algorithm

Looking forward in learning and master my skills in DSA. 

## Milestones
- [x] Code for 30 days
- [ ] Be able to complete 1 or 2 projects, ,
- [ ] Study and be firm in data structures platform,
- [ ] enhance and prepare my skills to get into dream companies 
- [ ] Complete My Udemy course in Blockchain and Python
- [ ] Learn HTML,CSS,JS 
- [ ] Be able to code for face recognition 

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by Rahul-on-github** [comment]
DAY 1 : STARTED HTML basics and UDEMY course on blockchain
