### ISSUE TITLE
[PROGRESS] annamalaiprabu

### ISSUE THREAD

**Issue by annamalaiprabu** [Codezilla-Club/30-Days-of-Code#54]
## Participant Details
**Name/Nickname:** Annamalai Prabu
**Pronouns:** he/him
**Domain:** Web Development

< Hi there! I am Annamalai and a first year undergrad at SRM RMP. I hope to learn a lot throughout these 30 days -->

## Milestones
- [ ] Code for 30 days
- [ ] Learn HTML CSS from freecodecamp.org
- [ ] Learn JavaScript, Node JS and MySQL

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by annamalaiprabu** [comment]
Day 1

What I Learned Today

- Explored the Roadmap provided to me and analyzed my present position with regard to Web Development
- Choose a suitable course for HTML CSS
- Learnt how to update Daily Progress Tracker
- Clarified a few doubts I had with my mentors

What I'll Learn Tomorrow

- Study HTML CSS for 6 Hours from my chosen course

**Comment by charitharyan** [comment]
Hey Annamalai, please do join the discord server as soon as possible
https://discord.gg/RTamqMWnTb
