### ISSUE TITLE
[PROGRESS] arul17gupta

### ISSUE THREAD

**Issue by arul17gupta** [Codezilla-Club/30-Days-of-Code#55]
## Participant Details
**Name/Nickname:** Arul 
**Pronouns:** he/him
**Domain:** Web Dev

## Milestones
- [x] Code for 30 days
- [x]  To Learn Full Stack Web development 
- [x] To clone McLaren Website 

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by arul17gupta** [comment]
Day 1

## What I Learned Today
How to update my progress on github

## What I'll Learn Tomorrow
-

**Comment by arul17gupta** [comment]
Day 2

## What I Learned Today
I learned how to embed the vdo in html through iframe tag 
A little progress on the project.

## What I'll Learn Tomorrow

**Comment by charitharyan** [comment]
Hey Arul!
Please make sure all the 4 checkboxes are present in the Milestones section.

**Comment by arul17gupta** [comment]
> Hey Arul! Please make sure all the 4 checkboxes are present in the Milestones section.

There 3 of them in milestone so r u saying to do it 4 @charitharyan

**Comment by arul17gupta** [comment]
Day 3

## What I Learned Today
Today I just laid some of the elements down 
I m out of town right now so can't do much progress

## What I'll Learn Tomorrow
-

**Comment by arul17gupta** [comment]
Day 4

## What I Learned Today
today i learned about positioning of elements what is relative absolute 

## What I'll Learn Tomorrow
-

**Comment by arul17gupta** [comment]
Day 5

## What I Learned Today
Today I added more layout and elements in my code 

## What I'll Learn Tomorrow
-

**Comment by arul17gupta** [comment]
Day 6 

## What I Learned Today
Today I learned About variables and strings in JavaScript

## What I'll Learn Tomorrow
-

**Comment by arul17gupta** [comment]
Day 7

## What I Learned Today
Today I added a bit of CSS into the website I aligned the divs 

## What I'll Learn Tomorrow
there is many more elements to go!!

**Comment by charitharyan** [comment]
> > Hey Arul! Please make sure all the 4 checkboxes are present in the Milestones section.
> 
> There 3 of them in milestone so r u saying to do it 4 @charitharyan

Yes please
