### ISSUE TITLE
[PROGRESS] en-peyar-arun

### ISSUE THREAD

**Issue by s-aruneshwaran** [Codezilla-Club/30-Days-of-Code#58]
## Participant Details
**Name/Nickname:** Arun S
**Pronouns:** He/Him
**Domain:** Android development

## Milestones
- [ ] Code for 30 days

- [ ] To learn android development

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by s-aruneshwaran** [comment]
Day 1

## What I Learned Today
-  Overview of android studio
-  Basics of kotlin

## What I'll Learn Tomorrow
-  kotlin in depth
