### ISSUE TITLE
[PROGRESS] ak2704

### ISSUE THREAD

**Issue by akash2704** [Codezilla-Club/30-Days-of-Code#61]
## Participant Details
**Name/Nickname:**Akash
**Pronouns:**he/him
**Domain:**Web development

Hi, my name is Akash Kallai I am a CSE AIML student at SRMKTR I love coding in general . 
## Milestones
- [X] Code for 30 days

- [ ] I want to learn Javascript
- [ ] I want to be able to show my projects during my interview for internships and job searching.
- [ ] I want to complete 3 projects.

## Checklist
- [X] I've read the Code of Conduct, Rules and Guidelines
- [X] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by akash2704** [comment]
Day 1

## What I Learned Today
- I completed full Html today 

## What I'll Learn Tomorrow
-Tomorrow I will be completing CSS and will start on my portfolio project

**Comment by charitharyan** [comment]
Hey Akash!
Please check the alignment and styling of your 'Participant Details'.
