### ISSUE TITLE
[PROGRESS] PRAWIN392

### ISSUE THREAD

**Issue by PRAWIN392** [Codezilla-Club/30-Days-of-Code#62]
## Participant Details
**Name/Nickname:** Prawin
**Pronouns:** he/him
**Domain:** Machine learning

Hi , i am prawin from SRMIST , RAMAPURAM , i am a AI/ML enthusiast..

## Milestones
- [ ] Code for 30 days

- [ ] Complete the Machine learning course with python in coursera.
- [ ] Build a couple machine learning models.

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by PRAWIN392** [comment]
Day 1

## What I Learned Today
- I started  learning Object oriented progamming in python

**Comment by PRAWIN392** [comment]
Day 2

## What I Learned Today
- I finished Object oriented programming in python

## What I'll Learn Tomorrow
- Basic markdown

**Comment by PRAWIN392** [comment]
Day 3

## What I Learned Today
- Saw a basic and overview of Machine of learning algorithms.

## What I'll Learn Tomorrow
- Will start the ML algorthims one by one in deep.

**Comment by PRAWIN392** [comment]
Day 6

## What I Learned Today
-  learned about linear regression

## What I'll Learn Tomorrow
- will learn about logistic regression

**Comment by PRAWIN392** [comment]
Day 7

## What I Learned Today
- completed learning logistic regression

## What I'll Learn Tomorrow
- will learn pandas, numpy and matplotlib

**Comment by PRAWIN392** [comment]
Day 8


## What I Learned Today
-  learned about python libraries such as pandas, numpy etc

## What I'll Learn Tomorrow
-  will explore about reinforcement learning

**Comment by PRAWIN392** [comment]
Day 9

## What I Learned Today
-  learnt about reinforcement learning

## What I'll Learn Tomorrow
-  will learn about How ML model works

**Comment by PRAWIN392** [comment]
Day 10

## What I Learned Today
-  i learnt how ml model works

## What I'll Learn Tomorrow
- i will start woking on a ml model

**Comment by GopinathBalaji** [comment]
Hey Pravin
Please upload your week1 and week2 projects at the earliest

**Comment by PRAWIN392** [comment]
Day 11

## What I Learned Today
- Just started working on a ML model
