### ISSUE TITLE
[PROGRESS] pranav-on-github

### ISSUE THREAD

**Issue by pranav-on-github** [Codezilla-Club/30-Days-of-Code#63]
## Participant Details
Name/Nickname: Pranav
Pronouns: He/Him
Domain: Machine learning

I am AI and ML Enthusiast and I hope to learn as much as possible in this track

## Milestones
- [x] Code for 30 days

- [ ] complete a certification course on machine learning
- [x] to complete tow projects on creating an ML model
- [x] to learn python at intermediate level
- [x] to create a ML model of my own

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by pranav-on-github** [comment]
Day 1

## What I Learned Today
-  i learned about object oriented programming in python

**Comment by pranav-on-github** [comment]
Day 2

## What I Learned Today
-  i just revised the oops concept in python

## What I'll Learn Tomorrow
-  basic markdown

**Comment by pranav-on-github** [comment]
Day 4

## What I Learned Today
-  explored about machine learning algorithms

## What I'll Learn Tomorrow
-  will go deeper into it :)

**Comment by pranav-on-github** [comment]
Day 6

## What I Learned Today
-  learned about linear regression and it's uses

## What I'll Learn Tomorrow
-  will learn about logistic regression

**Comment by pranav-on-github** [comment]
Day 7

## What I Learned Today
- completed learning logistic regression

## What I'll Learn Tomorrow
- will learn the libraries such as pandas, matplotlib and numpy

**Comment by pranav-on-github** [comment]
Day 8
## What I Learned Today
-  explored about reinforcement learning

## What I'll Learn Tomorrow
-  will learn about unsupervised algorithms

**Comment by pranav-on-github** [comment]
Day 9

## What I Learned Today
-  learned about how ML algorithm works

## What I'll Learn Tomorrow
-  will learn about how to create an ML model

**Comment by pranav-on-github** [comment]
Day 10

## What I Learned Today
-  started building an machine learning model

## What I'll Learn Tomorrow
-  will complete the remaining process in it

**Comment by pranav-on-github** [comment]
Day 11

## What I Learned Today
-  will  start with another ML project

## What I'll Learn Tomorrow
-  for that will start collecting the data's from kaggle

**Comment by pranav-on-github** [comment]
Day 12
## What I Learned Today
-  understanding significance of confusion matrix and box plots

## What I'll Learn Tomorrow
-  perform exploratorty data analytics

**Comment by pranav-on-github** [comment]
Day 13

## What I Learned Today
-  learned and performed exploratory data analytics

## What I'll Learn Tomorrow
-  will go deeper into the topic and try to understand the things in an efficient manner

**Comment by pranav-on-github** [comment]
Day 14

## What I Learned Today
-  updated my previous machine learning model  just to brush up with the concepts

## What I'll Learn Tomorrow
-  will try to create a clone of my previous model just for the sake of practice

**Comment by pranav-on-github** [comment]
Day 15

## What I Learned Today
-  collected the raw data's for my clone molel

## What I'll Learn Tomorrow
-  will move towards step two of the model creation

**Comment by pranav-on-github** [comment]
Day 16

## What I Learned Today
-  done the coding part of my clone model

## What I'll Learn Tomorrow
-  will complete the entire model within tomorrow

**Comment by pranav-on-github** [comment]
Day 17

## What I Learned Today
-  done with the entire machine learning clone model

## What I'll Learn Tomorrow
-  will start revising oops concepts in python

**Comment by pranav-on-github** [comment]
Day 18

## What I Learned Today
-  explored about data analytics

## What I'll Learn Tomorrow
-  will go deeper into it

**Comment by pranav-on-github** [comment]
Day 19

## What I Learned Today
-  learned about data analytics 

## What I'll Learn Tomorrow
-  will explore the job of a data analyst

**Comment by pranav-on-github** [comment]
Day 20

## What I Learned Today
-  learned about the basics of ms execel

## What I'll Learn Tomorrow
-  will start learn about the KPMG Data analytics course

**Comment by pranav-on-github** [comment]
Day 21

## What I Learned Today
-  started with KPMG Data analytics course

## What I'll Learn Tomorrow
-  will carry on with the progress of data analytics virtual internship

**Comment by pranav-on-github** [comment]
Day 20

## What I Learned Today
-   completed the phase 1 of data analytics virtual internship

## What I'll Learn Tomorrow
-   will begin with the second phase from tomorrow onwards

**Comment by pranav-on-github** [comment]
Day 21

## What I Learned Today
-  started with the phase 2 of data analytics virtual internship

## What I'll Learn Tomorrow
-   will start to learn about the advanced excel

**Comment by pranav-on-github** [comment]
Day 22

## What I Learned Today
-  started with advanced excel along with the phase 2 of data analytics virtual internship

## What I'll Learn Tomorrow
-  will try to complete the phase 2 of data analytics program within tomorrow

**Comment by pranav-on-github** [comment]
Day 23

## What I Learned Today
-  on the progress in the phase 2 of data analytics program

## What I'll Learn Tomorrow
-  will start exploring about microsoft power BI

**Comment by pranav-on-github** [comment]
Day 24

## What I Learned Today
-  started the learn Microsoft Power BI

## What I'll Learn Tomorrow
-   Will try to complete the the phase 2 of data analytics course

**Comment by pranav-on-github** [comment]
Day 25

## What I Learned Today
-  completed the phase 2 of data analytics course

## What I'll Learn Tomorrow
-  will try to solve the real world problems related to data analytics

**Comment by pranav-on-github** [comment]
Day 26

## What I Learned Today
-  started with the problems with data analytics

## What I'll Learn Tomorrow
-  will continue the problem solving journey

**Comment by pranav-on-github** [comment]
Day 29

## What I Learned Today
-  almost nearing with the data analytics course by KPMG

## What I'll Learn Tomorrow
-  end of ML journey, but still continue my learnings :)

**Comment by pranav-on-github** [comment]
HERE I HAVE ATTACHED SOME OF MY PROJECTS DURING THESE 30 DAYS OF MY JOURNEY, I'M PROUD TO SHARE THIS. THOUGH IT WAS A SIMPLE ONE, IT WAS AN INTERMEDIATE  LEVEL. IF YOU WANT ME TO SHOW SOME MORE PROJECTS, THEN DEFINENTLY I WILL ATTACH HERE

https://github.com/pranav-on-github/C-zilla-30-days-of-code

**Comment by pranav-on-github** [comment]
MY 30 days contribution
https://github.com/pranav-on-github/C-zilla-30-days-of-code
