### ISSUE TITLE
[PROGRESS] Shubham10

### ISSUE THREAD

**Issue by shubhamprabhu10** [Codezilla-Club/30-Days-of-Code#64]
## Participant Details
**Name/Nickname:** Shubham
**Pronouns:** He/Him
**Domain:** DSA

I'm an ML/DS Enthusiast who's excited to be here to learn and be a part of this program!

## Milestones
- [ ] Code for 30 days
- [ ] Learn Stacks
- [ ] Learn Queues and its types
- [ ] Learn Trees and its types
- [ ] Learn Graphs and its types
- [ ] Learn Hashing

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by shubhamprabhu10** [comment]
Today I learnt basics about DSA and various types it has

**Comment by shubhamprabhu10** [comment]
Tomorrow I'll learn about particular DS  starting with arrays and solve a few HR problems on the same topic
