### ISSUE TITLE
[PROGRESS] Ash-Codename47

### ISSUE THREAD

**Issue by ashwinkumar-jk** [Codezilla-Club/30-Days-of-Code#65]
## Participant Details
**Name/Nickname:** Ash
**Pronouns:** He/Him
**Domain:** Web Development

An enthusiastic coder!

## Milestones
- [ ] Code for 30 days

- [ ] To be consistent
- [ ] I wanna learn more Frontend Web dev and implement on website 
- [ ] React.js

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by ashwinkumar-jk** [comment]
Day 1

## What I Learned Today
- I refreshed the basics of Html

## What I'll Learn Tomorrow
-  I'll go through CSS

**Comment by ashwinkumar-jk** [comment]
Day 2

## What I Learned Today
-  I refreshed the basics of CSS

## What I'll Learn Tomorrow
- I'll go through Javascript

**Comment by charitharyan** [comment]
Hey Ash!
Please make sure all the 4 checkboxes are present in the Milestones section.

**Comment by ashwinkumar-jk** [comment]
Day 3

## What I Learned Today
- I refreshed DOM manipulation in javascript

## What I'll Learn Tomorrow
- I'll continue with javascript
