### ISSUE TITLE
[PROGRESS] Saurav2120

### ISSUE THREAD

**Issue by Saurav2120** [Codezilla-Club/30-Days-of-Code#66]
## Participant Details
**Name/Nickname:**Saura
**Pronouns:**He/Him
**Domain:** Data Structures & Algorithms

 I'm here to make some progress in DSA and to improve my programming skills.

## Milestones
- [ ] Code for 30 days
- [ ] I want to be consistent and to learn new things every day
- [ ] Array
- [ ] Linked list
- [ ] stacks
- [ ] Queue
- [ ] searching
- [ ] sorting
- [ ] Tree
- [ ] Graph

## Checklist
- [X] I've read the Code of Conduct, Rules and Guidelines
- [X] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by Saurav2120** [comment]
Day 1

## What I Learned Today
- Started Learning DSA using the C language.
- Basics of C language.

## What I'll Learn Tomorrow
- Basics of Data Structures.

**Comment by Saurav2120** [comment]
Day 2

## What I Learned Today
- Understands Basics of Data Structures.
- Learned Time & Space Complexity.

## What I'll Learn Tomorrow
- I'll learn Abstract Datatypes.

**Comment by Saurav2120** [comment]
Day 3

## What I Learned Today
- Learned about Abstract Datatypes.

## What I'll Learn Tomorrow
- I'll Learn About Time & Space Complexity

**Comment by Saurav2120** [comment]
Day 4

## What I Learned Today
- I Learned Time & Space complexity.
- Like worst,avg., best case complexity.

## What I'll Learn Tomorrow
- I'll Start with Arrays.
