### ISSUE TITLE
[PROGRESS] Harsh_Jain

### ISSUE THREAD

**Issue by ghost** [Codezilla-Club/30-Days-of-Code#67]
## Participant Details
**Name/Nickname:** Harsh Jain
**Pronouns:** He/Him
**Domain:** DSA

I am here to learn and improve my concepts of DSA

## Milestones
- [ ] Code for 30 days

- [x] Arrays
- [ ] Strings
- [ ] Linked List
- [ ] Stack
- [ ] Queue
- [ ] Tree
- [ ] Graph
## Checklist
- [x] I've read the Code of Conduct, Rules, and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by ghost** [comment]
Day 1

## What I Learned Today
-  Selected C++ as a language to start DSA
- Basics of Language 

## What I'll Learn Tomorrow
- Basics of Data Structure

**Comment by ghost** [comment]
Day 2

## What I Learned Today
-  basics of data structure 

## What I'll Learn Tomorrow
- array

**Comment by ghost** [comment]
Day 3

## What I Learned Today
- Introduction to array
- operations in array
- solved couple of questions

## What I'll Learn Tomorrow
- start Link list

**Comment by ghost** [comment]
Day 4

## What I Learned Today
- Started link list 
- solved 5 problems 

## What I'll Learn Tomorrow
- types of link list and their operations

**Comment by ghost** [comment]
Day 5

## What I Learned Today
- completed operations on the link list

## What I'll Learn Tomorrow
- types of link list

**Comment by ghost** [comment]
Day 6

## What I Learned Today
- types of link list

## What I'll Learn Tomorrow
- types of link list 
- strings
