### ISSUE TITLE
[PROGRESS] Saikiran-on-github

### ISSUE THREAD

**Issue by Saikiran-on-github** [Codezilla-Club/30-Days-of-Code#68]
## Participant Details
**Name/Nickname:** Saikiran
**Pronouns:** he/him
**Domain:** Web Development

Web enthusiast.
## Milestones
- [ ] Code for 30 days

- [ ] Become good at front end and also learn backend development
## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by Saikiran-on-github** [comment]
Day 1

## What I Learned Today
- Some internet basics

## What I'll Learn Tomorrow
- Basics of GIT

**Comment by Saikiran-on-github** [comment]
Day 2

## What I Learned Today
- learnt basics of git

## What I'll Learn Tomorrow
-learn github and try to start http
