### ISSUE TITLE
[PROGRESS] Ishtiaq310

### ISSUE THREAD

**Issue by Ishtiaq310** [Codezilla-Club/30-Days-of-Code#69]
## Participant Details
**Name/Nickname:** Ishtiaq
**Pronouns:** He/Him
**Domain:** Data Structures and Algorithms

## Milestones
- [x] Code for 30 days
- [ ] Be good in DSA.
- [ ] Solve DSA problems.
## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by Ishtiaq310** [comment]
Day 1

## What I Learned Today
- Went through the basics of DSA.
- Arrays, Linked List, Stack, Queue.

## What I'll Learn Tomorrow
- Tomorrow I will start arrays.

**Comment by Ishtiaq310** [comment]
Day 2

## What I Learned Today
- Studied arrays and need and it's advantages.
-  Got introduced to its basic operations.
## What I'll Learn Tomorrow
- Take one operation and study it.

**Comment by Ishtiaq310** [comment]
Day 4

## What I Learned Today
- Linear Search

## What I'll Learn Tomorrow
- Binary Search
-

**Comment by Ishtiaq310** [comment]
Day 5

## What I Learned Today
- Binary Search 

## What I'll Learn Tomorrow
- Bubble Sort
