### ISSUE TITLE
Vishal-Aravind

### ISSUE THREAD

**Issue by Vishal-Aravind** [Codezilla-Club/30-Days-of-Code#70]
## Participant Details
**Name/Nickname:**Vishal
**Pronouns:**he/him
**Domain:**Data structures and algorithms

Optionally left!! XD

## Milestones
- [x] Code for 30 days

Get a clear idea on the days of progress

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by Vishal-Aravind** [comment]
Day 2

##What I learned today --
Introduction and syntaxes

##What I will learn tomorrow--
Efficiency

**Comment by Vishal-Aravind** [comment]
Day 3

##What I learned today--
Efficiency and worst case 

##What I will learn tomorrow--
Approximation

**Comment by Vishal-Aravind** [comment]
Day 4

##What I learned today--
Approximation and collections

##What I will learn tomorrow--
Lists and stack

**Comment by Vishal-Aravind** [comment]
Day 5

##What I learned today--
Lists and stack (details and practice)

## What I will learn tomorrow--
Queue

**Comment by Vishal-Aravind** [comment]
Day 6

##What I learned today--
Queue (Enqueue and Dequeue)

##What I will learn tomorrow--
Recursion

**Comment by Vishal-Aravind** [comment]
Day 7

##What I learned today--
Recursion and intro to sorting

##What I will learn tomorrow--
Types of sorting

**Comment by Vishal-Aravind** [comment]
Day 8

##What I learned today--
Bubble, quick, merge sort

##What I will learn tomorrow--
Maps

**Comment by Vishal-Aravind** [comment]
Day 9

##What I learned today--
Maps and hashing

##What I will learn tomorrow--
load factor, hash maps and string keys
