### ISSUE TITLE
[PROGRESS] Rohith_on_github

### ISSUE THREAD

**Issue by Rohithv04** [Codezilla-Club/30-Days-of-Code#71]
## Participant Details
**Name/Nickname:** Rohith
**Pronouns:** He/ Him
**Domain:** DSA

Hi, this is Rohith, I'm from CSBS SRMRMP. I am a completely new person to DSA. I'm here to make some progress in DSA and learn new things and improve my consistency.
## Milestones
- [ ] Code for 30 days
- [ ] Learn Python DSA 
- [ ] To create my own roadmap for Data science 
- [ ] To create 1 or 2 projects through my learning

## Checklist
- [ ] I've read the Code of Conduct, Rules and Guidelines
- [ ] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by Rohithv04** [comment]
Day 1

## What I Learned Today
I've got some reliable resources to learn DSA, and also planned my everyday time schedule to do coding tasks. I've learnt about algorithms and data structures and their types

## What I'll Learn Tomorrow
Few concepts about Data Structures 
- Stack
- Queues
- Types of Queues
