### ISSUE TITLE
[PROGRESS] Gokulakrishnan-r

### ISSUE THREAD

**Issue by Gokulakrishnan-r** [Codezilla-Club/30-Days-of-Code#73]
## Participant Details
Name/Nickname: Gokula Krishnan R
Pronouns: he/him
Domain: Data Structures and Algorithms

I am a Front-end Developer 

 Milestones
- [x] Code for 30 days
- [ ] To make sure I learn DSA concepts
- [ ] To be consistent.

 Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I have been assigned a mentor

**Comment by Gokulakrishnan-r** [comment]
Day 1

## What I Learned Today
- Had a look on the resources shared.  
- surfed about DS in youtube. 
- Array 


## What I'll Learn Tomorrow
- to solve DS related problems in Hackerank
- to get better understanding about DS and array.

**Comment by Gokulakrishnan-r** [comment]
Day 2

## What I Learned Today
- Array 
- array rotation 

## What I'll Learn Tomorrow
- to solve few problems on Array

**Comment by Gokulakrishnan-r** [comment]
Day 3

## What I Learned Today
- started with array rotation, but couldn't finish it up.  

## What I'll Learn Tomorrow
- array again :)

**Comment by Gokulakrishnan-r** [comment]
Day 4

## What I Learned Today
- Hackerrank DS problems 

## What I'll Learn Tomorrow
- Solving problems on arrays
