### ISSUE TITLE
[PROGRESS] SairamNomula

### ISSUE THREAD

**Issue by SairamNomula** [Codezilla-Club/30-Days-of-Code#74]
## Participant Details
**Name/Nickname: Venkata Naga Sai Ram Nomula**
**Pronouns: he/him**
**Domain: Data Structures and Algorithms**

## Milestones
- [ ] Code for 30 days
- [ ] Learn DSA concepts
- [ ] **Maintain Consistency**

## Checklist
- [x] I've read the Code of Conduct, Rules, and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by SairamNomula** [comment]
Day 1

## What I Did Today
- Connected with the community.
- Created an issue in the respective Github repo.
- Found a youtube video to follow from tomorrow on Java. 

## What I'll Learn Tomorrow
- Basics of Java from JavaTPoint.

**Comment by SairamNomula** [comment]
Day 2

## What I Did Today
- Started learning Java from JavaTPoint.
- Referred Telusko Youtube channel for some concepts. 

## What I'll Learn Tomorrow
- Will learn about Java Object Class.

**Comment by SairamNomula** [comment]
Day 3

## What I Did Today
- Learned about Java Object class
- Completed arrays part in java
- Practiced some array problems using java

## What I'll Learn Tomorrow
- OOPs Concept in Java

**Comment by SairamNomula** [comment]
Day 4

## What I Did Today
- Practiced some problems.
- Revised what I did yesterday
- Started OOPs concept in Java

## What I'll Do Tomorrow
- Will try to complete OOPs Concept in Java
