### ISSUE TITLE
[PROGRESS]chaitanya ambati 

### ISSUE THREAD

**Issue by chai1323** [Codezilla-Club/30-Days-of-Code#75]
## Participant Details
**Name/Nickname:**chaitu 
**Pronouns:**her
**Domain:**web dev

## Milestones
- [x] Code for 30 days
- [ ] interview preparation 

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by Akshara604** [comment]
Hi chaitu
Just a few corrections

- Check the markdown in the intro
- Add some more milestones
- Use the template given in ReadMe to update your progress daily

**Comment by chai1323** [comment]
> ## Participant Details
> **Name/Nickname:**chaitu 
> **Pronouns:**her
> **Domain:**web dev
> 
> 
> 
> ## Milestones
> - [x] Code for 30 days
> - [ ]interview preparation 
> 
> 
> 
> 
> ## Checklist
> - [x] I've read the Code of Conduct, Rules and Guidelines
> - [x] I've named this Issue as indicated
> - [ ] I've been assigned a mentor

**Comment by chai1323** [comment]
Day 9

## What I Learned Today
- css animations , colour scheme

## What I'll Learn Tomorrow
- css animation adavanced
