### ISSUE TITLE
[PROGRESS] aghosh0605

### ISSUE THREAD

**Issue by ghoshzsh** [Codezilla-Club/30-Days-of-Code#77]
## Participant Details
**Name/Nickname:** Aniruddha
**Pronouns:** he/him
**Domain:** Web Development

## Milestones
- [x] Code for 30 days
- [x] Make a Full stack website in Typescript

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by ghoshzsh** [comment]
## Day 1

I started learning **Typescript, MongoDB, NextJs Routes**

**Comment by charitharyan** [comment]
Hey Aniruddha!
Please make sure all the 4 checkboxes are present in the Milestones section.

**Comment by ghoshzsh** [comment]
Between these three days, I completed the below things
- MongoDB CRUD operations
- MongoDB connect code in Typescript
- A NextJS GET API to fetch MongoDB data

**Comment by ghoshzsh** [comment]
Today I completed these things:
1. [Typescript Basic Types](https://github.com/aghosh0605/Understanding-TS-2022/tree/02-TS_Basics_and_Basic_Types)

**Comment by charitharyan** [comment]
Hey there, please follow the templated order of daily attendance

**Comment by ghoshzsh** [comment]
Along these days I am learning typescript and developing a website.
1. Learning Repo [here](https://github.com/aghosh0605/Understanding-TS-2022/commits/02-TS_Basics_and_Basic_Types)
2. Project site URL [here](http://htbsrmist.tech)

**Comment by ghoshzsh** [comment]
Today I learned
1. Singleton Function for MongoDB Connect 
2. Typescript Class and Objects

**Comment by ghoshzsh** [comment]
Today I learned
1. Basics of Flask
2. Dockerizing a Flask App

**Comment by ghoshzsh** [comment]
Today I learned
1. Slug API in Express
2. Express Routes

**Comment by ghoshzsh** [comment]
Today I learnt
1. Express API
2. Middlewares

**Comment by ghoshzsh** [comment]
Today I learnt
1. Python to learn Django
2. Bash Scripting

**Comment by ghoshzsh** [comment]
Today I learnt
1. Cors Policy 
2. Vercel Deployment

**Comment by ghoshzsh** [comment]
Today I learnt
1. JWT
2. Validating User Input
3. Using CORS
