### ISSUE TITLE
[PROGRESS] srinivas1904code

### ISSUE THREAD

**Issue by srinivas1904code** [Codezilla-Club/30-Days-of-Code#79]
## Participant Details
**Name/Nickname:**s.srinivas
**Pronouns:**he/him
**Domain:**machine learning

I am super excited in learning new things.
Appling the concept learned gives me satisfaction.
## Milestones
- [ ] Code for 30 days

- [ ] Apply machine learning in real time problem
## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by srinivas1904code** [comment]
Day 1

## What I Learned Today
- data analytics with python( 1st video).
- downloaded anaconda software.

## What I'll Learn Tomorrow
- Next resource lecture and practice.

**Comment by srinivas1904code** [comment]
Day 2

## What I Learned Today
- learnt basic operations that can be performed using pandas on excel sheet

## What I'll Learn Tomorrow
- next resource

**Comment by srinivas1904code** [comment]
Day 3

## What I Learned Today
- access different rows and commands, different, visualization techniques

## What I'll Learn Tomorrow
- object oriented programming using python

**Comment by srinivas1904code** [comment]
Day 4

## What I Learned Today
- functions using python

## What I'll Learn Tomorrow
- classes using python

**Comment by srinivas1904code** [comment]
Day 5

## What I Learned Today
- Practiced few examples on functions.
- Done and uploaded week one assignment in repo

## What I'll Learn Tomorrow
- classes in python, week 2 references
