### ISSUE TITLE
[PROGRESS] sriniharish

### ISSUE THREAD

**Issue by SriniHarish** [Codezilla-Club/30-Days-of-Code#81]
## Participant Details
**Name/Nickname:**Srini
**Pronouns:**He
**Domain:**DSA

I'm Srini, 
I have completed my UG in B.Tech Mechanical engineering and worked as Java microservice developer for couple of years.
I have interest in Data science.
I'm currently pursuing my PG in MBA-Data Analytics
## Milestones
- [x] Code for 30 days

1.To learn and understand DSA 
2.To get hands-on experience in DSA

## Checklist
- [x ] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by SriniHarish** [comment]
Day 6

## I have learned basic DSA used in Python
- 

## Coming week I will try to solve more codes using Array, List in Python
-
