### ISSUE TITLE
[PROGRESS] Vartika511

### ISSUE THREAD

**Issue by Vartika511** [Codezilla-Club/30-Days-of-Code#83]
## Participant Details
**Name/Nickname:** Vartika Yaduvanshi
**Pronouns:** She
**Domain:** Web Development

## Milestones
- [x] Code for 25 days
- [x]  To complete the Full Course of Three JS
- [x]  To make a Basic Website Using Three JS
- [x]  To make group project by integrating SAWO API 

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by Vartika511** [comment]
Day 1

## What I Learned Today
- I learned about Physics.js
- Did open source contribution by using js

## What I'll Learn Tomorrow
- To implement physic.js and make a small cool project

**Comment by Vartika511** [comment]
Day 2

## What I Learned Today
- Made a small project using physics.js

## What I'll Learn Tomorrow
- Learn basics of Blender

**Comment by Vartika511** [comment]
Day 3

## What I Learned Today
- made a basic model using blender 

## What I'll Learn Tomorrow
- will  create a scene using Blender

**Comment by Vartika511** [comment]
Day 4

## What I Learned Today
- Today I made the layout of my website for Threejs project collection

## What I'll Learn Tomorrow
- I will create a login page using SAWO and create scene in blender

**Comment by Vartika511** [comment]
Day 5

## What I Learned Today
-  Made the Login Page of my website and also Integrated it

## What I'll Learn Tomorrow
- Will make the landing page of website

**Comment by Vartika511** [comment]
Day 6

## What I Learned Today
- Made a project for Open Source Contribution.

## What I'll Learn Tomorrow
- Will work on my website

**Comment by Vartika511** [comment]
Day 7

## What I Learned Today
- Started with another project for upcoming Hackathon gathered the required API's and have started working on it 

## What I'll Learn Tomorrow
- Will learn more about API's

**Comment by Vartika511** [comment]
Day 8

## What I Learned Today
- Used NASA API in my website and made the landing page 

## What I'll Learn Tomorrow
- To complete the different sections of website

**Comment by Vartika511** [comment]
Day 9

## What I Learned Today
- Worked on the project for hackathon, made a dashboard design  

## What I'll Learn Tomorrow
- Tomorrow I do backend work for the project

**Comment by Vartika511** [comment]
Day 10

## What I Learned Today
- Started Learning Python 

## What I'll Learn Tomorrow
- Will learn more about Python

**Comment by Vartika511** [comment]
Day 11

## What I Learned Today
- MADE BACKEND FOR LOGIN PAGE

## What I'll Learn Tomorrow
- will learn about shadows in three.js

**Comment by Vartika511** [comment]
Day 12

## What I Learned Today
- Learned how to import models from Blender to Threejs scene

## What I'll Learn Tomorrow
- I will make a galaxy with a debug panel

**Comment by Vartika511** [comment]
Day 13

## What I Learned Today
- Started making  my portfolio design on blender

## What I'll Learn Tomorrow
- will work more on designing my portfolio

**Comment by Vartika511** [comment]
Day 14

## What I Learned Today
- Worked on designing part of portfolio on blender 

## What I'll Learn Tomorrow
- will start importing textures tomorrow

**Comment by Vartika511** [comment]
Day 15

## What I Learned Today
- Make my 2 nd page for the Threejs website 

## What I'll Learn Tomorrow
- will export it from threejs and import it my website tommorow

**Comment by Vartika511** [comment]
Day 16

## What I Learned Today
- Completed with my 2nd page just have to solve some glitches.

## What I'll Learn Tomorrow
- I will work on improving dashboard of group project tomorrow

**Comment by Vartika511** [comment]
Day 17

## What I Learned Today
- Worked on the group project make the dashboard and prepared the basic design for Booking Auditorium Page.

## What I'll Learn Tomorrow
- Will work on the implementation of the Auditorium boking page

**Comment by Vartika511** [comment]
Day 18

## What I Learned Today
- Completed with Frontend part of booking page will work on the backend part of it 

## What I'll Learn Tomorrow
- Will solve some glitches of my personal website and host it

**Comment by Vartika511** [comment]
Day 19

## What I Learned Today
- Hosted my website it took a lot of time.

## What I'll Learn Tomorrow
- Will work on the group project

**Comment by Vartika511** [comment]
Day 20

## What I Learned Today
- Worked on the backend part of Sign up page and on the booking page 

## What I'll Learn Tomorrow
- Will work on the Mass mailing and mass messaging part

**Comment by Vartika511** [comment]
Day 21

## What I Learned Today
- Did backend part of mass mailing still there is some issue

## What I'll Learn Tomorrow
- Will solve issue of mass mailing part

**Comment by Vartika511** [comment]
Day 22

## What I Learned Today
- Completed with backend part of mass mailing and mass messaging 

## What I'll Learn Tomorrow
- Will complete the name selection page

**Comment by Vartika511** [comment]
Day 23

## What I Learned Today
- Made the name selection page and connected it with backend so only selected people gets the mail

## What I'll Learn Tomorrow
- Will work more on the backend part

**Comment by Vartika511** [comment]
Day 24

## What I Learned Today
- Completed with backend part connected the mass mailing server with name selection page

## What I'll Learn Tomorrow
- Will do run dry and host the website

**Comment by Vartika511** [comment]
Day 25

## What I Learned Today
- Checked everything and Hosted the website

## THANK YOU CODEZILLA FOR THIS OPORTUNITY ☺.
