### ISSUE TITLE
[PROGRESS] swati

### ISSUE THREAD

**Issue by swati-77** [Codezilla-Club/30-Days-of-Code#84]
## Participant Details
**Name/Nickname:**swati
**Pronouns:**her
**Domain:**dsa

## Milestones
- [ ] Code for 30 days

 - [ ] learn dsa from basics
- [ ]  be consistent
## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by swati-77** [comment]
Day 1

#What I learned today
- [ ] Connected with the community.
- [ ] Created an issue in the respective Github repo.
- [ ] Found a youtube video to follow from tomorrow on c++

##what I'll learn tomorrow
- [ ] learn basics of c++

**Comment by swati-77** [comment]
Day 1

**What I learned today**

- Connected with the community.
- Created an issue in the respective Github repo.
- Found a youtube video to follow from tomorrow on c++.

**what I'll learn tomorrow**

- learn basics of c++
