### ISSUE TITLE
[PROGRESS] ananthram002

### ISSUE THREAD

**Issue by ananthram-g** [Codezilla-Club/30-Days-of-Code#85]
## Participant Details
**Name/Nickname:** Ananth Ram
**Pronouns:** He/Him
**Domain:** DSA

## Milestones
- [ ] Code for 30 days

- [ ] Learn the basics of Data Structures
- [ ] Learn to write Algorithms for complex programs on my own.

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by ananthram-g** [comment]
Day 1

## What I Learned Today
- Basics of Data Structures

## What I'll Learn Tomorrow
- Arrays
