### ISSUE TITLE
[PROGRESS] prnv09

### ISSUE THREAD

**Issue by prnv09** [Codezilla-Club/30-Days-of-Code#86]
## Participant Details
**Name/Nickname:** Pranav
**Pronouns:**  He/Him
**Domain:** Web Development

I'm a blockchain and crypto explorer + learner. crazy to do something innovative, Started warana.online and looking for more ideas to start something.

## Milestones
- [ ] Code for 30 days
- [ ] Learn HTML,CSS,JS and NODE 
- [ ] Develop Certificate Issuing and Verification system
- [ ] Get familiar with color selection (I'm not good yet)

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by prnv09** [comment]
Day 2

## What I did Today
- Added my issue (pending work of Day1)
- Learnt about Git and Github, Gitlab
- Started interacting with new friends on Discord
- Read the roadmap of Web development

## What I'll do Tomorrow
- Start HTTP and HTTPS
- Learn about SDLC
- I'll get some information about project we have to complete in first week

**Comment by prnv09** [comment]
Day 3

## What I did Today
- What is SDLC
- Steps in SDLC
- SDLC Models
- HTTP vs HTTPS

## What I'll do Tomorrow
- try to get start with first week project
