### ISSUE TITLE
[PROGRESS] Nandhini0720

### ISSUE THREAD

**Issue by NandhiniLakshmipathy** [Codezilla-Club/30-Days-of-Code#88]
## Participant Details
**Name/Nickname:** Nandhini
**Pronouns:**she/her
**Domain:**DSA

## Milestones
- [ ] Code for 30 days
- [ ] assigned my mentor
- [x] Read the guide lines
- [ ] Completed the tasks

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [ ] I've been assigned a mentor

**Comment by NandhiniLakshmipathy** [comment]
Day1

## What I learnt today

- Introduction to web
- What is git and github
- Gone through the guidelines 

## What I do Tomorrow

- Revise the HTML tags
- Do practice it
