### ISSUE TITLE
[PROGRESS] saie-cyber

### ISSUE THREAD

**Issue by saie-cyber** [Codezilla-Club/30-Days-of-Code#89]
## Participant Details
**Name/Nickname:**Saierangan
**Pronouns:**he/him
**Domain:**Web Development

## Milestones
- [ ] Code for 30 days

-[ ] I want to learn about developing websites
-[ ] I want to develop a website 

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by saie-cyber** [comment]
Day 1

## What I Learned Today
- I learnt about basics and history of web development

## What I'll Learn Tomorrow
- I will have a glance of how different websites work

**Comment by saie-cyber** [comment]
Day 2

## What I Learned Today
- Had a glance of different websites

## What I'll Learn Tomorrow
- Have a glance of the coding part of different websites

**Comment by saie-cyber** [comment]
Day 3

## What I Learned Today
- Had a glance of the coding part of some websites

## What I'll Learn Tomorrow
- will try to learn some basic terms and functions in web development
