### ISSUE TITLE
[PROGRESS] Akshu-on-github

### ISSUE THREAD

**Issue by Akshu-on-github** [Codezilla-Club/30-Days-of-Code#9]
## Participant Details
**Name/Nickname:** Akshu
**Pronouns:** she/her
**Domain:** Android Development

## Milestones
- [ ] Code for 30 days

- [ ] I want to learn about Firebase
- [ ] I want to create 3 app frontends

## Checklist
- [x] I've read the Code of Conduct, Rules and Guidelines
- [x] I've named this Issue as indicated
- [x] I've been assigned a mentor

**Comment by Akshu-on-github** [comment]
Day 1

## What I Learned Today
- I learnt about Firebase

## What I'll Learn Tomorrow
- I'd like to implement a backend for my app

**Comment by rameshkumarm95** [comment]
Machine learning

**Comment by Akshu-on-github** [comment]
Day 2

## What I did Today
- Connected with the community! ✨
- Learnt about why Google created Kotlin 🍵 
- Found a really cool YouTube video on app development! 📹 
- Made sure my dev environment is ready for tomorrow 🦾 

## What I'll do Tomorrow
- Start working on practice frontend mockups on Figma
- Search for more references and resources

**Comment by Akshu-on-github** [comment]
Day 3

## What I Learned Today
- Created a simple [figma design](https://www.figma.com/file/z8vg5NCytDlHisdiP5RIc3/Untitled?node-id=0%3A1) to get the hang of things
- Hung out in the AD-VC where Ajeet walked us through the code and file structure of a 'Hello, world!' android app
- Learnt about the different kinds of views

## What I'll Learn Tomorrow
- Create my own 'Hello, world!' app
- Start working on the weekly task

**Comment by Akshu-on-github** [comment]
Day 4

## What I Did Today
- Created my 'hello, world' app - all systems are a go 🚀 
- Created a mockup for the front end of my weekly task submission 🎨 
- Looked through the basics of kotlin 📖 

## What I'll Do Tomorrow
- Will start converting my weekly task's mockup to code
- Participate in givecamp-memphis

**Comment by Akshu-on-github** [comment]
Day 6

## What I Did Today
- Looked up opensource apps on GitHub, found a few nice designs and functionalities to draw inspiration from
- Tried to make an app inspired by Tom Scott's best thing in the world video

## What I'll Do Tomorrow
- Try to implement what I made note of
- See if I can integrate the same into my project

**Comment by Akshu-on-github** [comment]
Day 7

## What I Did Today
- Explored various styles of navigation
- Learnt about accessibility in app design and architecture, and the accessibility suit

## What I'll Do Tomorrow
- Look into layouts
- Try to make my practice designs more accessible

**Comment by Akshu-on-github** [comment]
Closing this now!
